### ISSUE TITLE
define endpoint

### ISSUE THREAD

**Issue by yamakenji24** [oreotabetai/user-auth-jwt-python-api#1]
## need to define endpoint to authorize users
- /login

**Comment by wakatakeru** [comment]
My suggestion is below:

- `Users`: users information
  - `POST /users`: regist a user.
  - `GET /users/:username`: return information of a user if an authentication information is valid.
- `Login`: login function (return jwt)
  - `POST /login`: return jwt if an authentication information is valid.

**Comment by yamakenji24** [comment]
Maybe, we could create a signUp, Login Pages so that the user(student) can see whats going on. 
(this could be the task on another repository)

**Comment by wakatakeru** [comment]
We added `POST /users` endpoint for user registration (sign-up).

#7
